apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: advent-2023
  namespace: advent-2023
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "advent2.southcity.dev"
    secretName: letsencrypt-prod
  rules:
  - host: "advent2.southcity.dev"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: advent-2023
            port:
              number: 8080
